name: Fetch Projects

on: [push]

jobs:
  find_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch Last Updated Project
        id: find_project
        env:
          GH_TOKEN: ${{ secrets.ORG_GH_TOKEN }}  # Use the secret you created
          TEAM_TO_CHANNEL: "{ \"s24-4pm-1\": \"C071HLX6DM\", \"s24-4pm-2\": \"C06592UPS91\" }"
          TEAM: ${{ github.repository }}  # Adjust as needed
          ORG_NAME: "brownfield-team"  # Replace with your GitHub organization name
        run: |
          # Log in using the token without revealing it
          echo "${GH_TOKEN}" | gh auth login --with-token --hostname github.com --quiet || { echo "Login failed"; exit 1; }

          # Clear the token from the environment after login
          unset GH_TOKEN

          # Now use the GitHub API to fetch projects
          API_URL="https://api.github.com/orgs/${ORG_NAME}/projects"
          PROJECTS_JSON=$(curl -s -H "Authorization: token ${GH_TOKEN}" "${API_URL}")
          echo "Projects JSON Output: $PROJECTS_JSON"

          if [ $? -ne 0 ]; then
            echo "Failed to fetch projects"
            exit 1
          fi

          PROJECT_ID=$(echo "$PROJECTS_JSON" | jq -r ".[] | select(.name | endswith(\"${TEAM}\")) | .id" | head -n 1)

          if [ -z "$PROJECT_ID" ]; then
            echo "No project found for team $TEAM."
            exit 1
          fi

          echo "Found Project ID: $PROJECT_ID"
          echo "project_id=$PROJECT_ID" >> $GITHUB_ENV  # Set output in the new way
