name: Get Project Columns

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  workflow_dispatch:  # Manual trigger

jobs:
  get-project-id:
    name: Get Project ID
    runs-on: ubuntu-latest
    outputs:
      project_id: ${{ steps.get_id.outputs.project_id }}
    steps:
      - name: Fetch Project ID
        id: get_id
        shell: pwsh
        run: |
          # GraphQL query to fetch project ID
          $query = '{organization(login:"brownfield-team"){projectsV2(first:100){nodes{id,title,updatedAt}}}}'
          $headers = @{
              Authorization = "Bearer ${{ secrets.GH_TOKEN }}"
              "Content-Type" = "application/json"
          }
          $body = @{ query = $query } | ConvertTo-Json
          $response = Invoke-WebRequest -Uri "https://api.github.com/graphql" -Method Post -Headers $headers -Body $body
          Write-Host "Projects JSON Output: $($response.Content)"
          
          # Find the project ID based on title
          $projectID = ($response.Content | ConvertFrom-Json).data.organization.projectsV2.nodes | Where-Object { $_.title -like "*s24-4pm-1*" } | Select-Object -First 1 -ExpandProperty id
          
          if (-not $projectID) {
              Write-Host "No project found for team s24-4pm-1."
              exit 1
          }
          
          Write-Host "Found Project ID: $projectID"
          echo "project_id=$projectID" | Out-File -FilePath $env:GITHUB_ENV -Append  # Set output in the new way

  get-project-columns:
    name: Get Project Board Columns
    needs: get-project-id
    runs-on: ubuntu-latest
    outputs:
      columns: ${{ steps.project_columns.outputs.columns }}
    steps:
      - name: Fetch Project Board Columns
        id: project_columns
        shell: pwsh
        run: |
          # Get the Project ID from the previous step's output
          $PROJECT_ID = "${{ needs.get-project-id.outputs.project_id }}"
          
          # Construct the GraphQL query
          $query = @"
          {
            node(id: "$PROJECT_ID") {
              ... on ProjectV2 {
                id
                title
                updatedAt
                fields {
                  nodes {
                    ... on ProjectV2Field {
                      id
                      name
                    }
                  }
                }
              }
            }
          }
          "@

          # Define headers with the authorization token
          $headers = @{
              Authorization = "Bearer ${{ secrets.GH_TOKEN }}"
              "Content-Type" = "application/json"
          }
          
          # Create the request body
          $body = @{ query = $query } | ConvertTo-Json
          
          # Send the request to the GitHub GraphQL API
          $response = Invoke-WebRequest -Uri "https://api.github.com/graphql" -Method Post -Headers $headers -Body $body
          
          # Output the response content for debugging
          Write-Host "Columns JSON Output: $($response.Content)"
          
          # Extract columns from response
          $columns = $response.Content | ConvertFrom-Json
          $columnData = $columns.data.node.fields.nodes | ConvertTo-Json
          
          # Set the output for columns
          echo "::set-output name=columns::$columnData"
