name: Fetch Projects

on: [push]

jobs:
  find_project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch Projects with PowerShell
        shell: pwsh  # Specify PowerShell as the shell
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use your GitHub token secret
          ORG_NAME: "brownfield-team"  # Replace with your GitHub organization name
          TEAM: "s24-4pm-1"  # Specify team name or adjust as needed
        run: |
          # Update the query to get the first 100 projects
          $query = '{organization(login:"brownfield-team"){projectsV2(first:100){nodes{id,title,updatedAt}}}}'
          $headers = @{
              Authorization = "Bearer $env:GH_TOKEN"
              "Content-Type" = "application/json"
          }
          $body = @{
              query = $query
          } | ConvertTo-Json

          $response = Invoke-WebRequest -Uri "https://api.github.com/graphql" -Method Post -Headers $headers -Body $body
          Write-Host "Projects JSON Output: $($response.Content)"

          # Parse JSON response and extract projects
          $projects = $response.Content | ConvertFrom-Json
          $sortedProjects = $projects.data.organization.projectsV2.nodes | Sort-Object -Property updatedAt -Descending

          # Find the first matching project for the specified team
          $projectID = $sortedProjects | Where-Object { $_.title -like "*$env:TEAM*" } | Select-Object -First 1 -ExpandProperty id

          if (-not $projectID) {
              Write-Host "No project found for team $env:TEAM."
              exit 1
          }

          Write-Host "Found Project ID: $projectID"
          "project_id=$projectID" | Out-File -FilePath $env:GITHUB_ENV -Append  # Set output in the new way
