name: Kanban Slack Update

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  workflow_dispatch:  # Allows manual triggering

env:
  PAT: ${{ secrets.PAT }}
  TEAM_TO_CHANNEL: "{ \"s24-4pm-1\": \"C071HLX6DMK\", \"s24-4pm-2\": \"C06592UPS91\" }"
  TEAM: ${{ github.repository }}
  ORG_NAME: "brownfield-team"  # Replace with your GitHub organization name

jobs:
  get-team-name:
    name: Get Team Name
    runs-on: ubuntu-latest
    outputs:
      team: ${{ steps.find_team.outputs.team }}
    steps:
      - name: Extract Team Name from Repo
        id: find_team
        run: |
          REPO=${{ github.repository }}
          TEAM_NAME="${REPO: -9}"
          echo "::set-output name=team::${TEAM_NAME}"
  get-project-id:
    name: Find Last Updated Project ID for Team
    runs-on: ubuntu-latest
    needs: get-team-name
    outputs:
      project_id: ${{ steps.find_project.outputs.project_id }}
    steps:
      - name: Fetch Project ID
        id: find_project
        shell: pwsh
        run: |
          $query = '{organization(login:"${{ env.ORG_NAME }}"){projectsV2(first:100){nodes{id,title,updatedAt}}}}'
          $headers = @{
              Authorization = "Bearer ${{ secrets.PAT }}"
              "Content-Type" = "application/json"
          }
          $body = @{ query = $query } | ConvertTo-Json
          $response = Invoke-WebRequest -Uri "https://api.github.com/graphql" -Method Post -Headers $headers -Body $body
          Write-Host "Projects JSON Output: $($response.Content)"
          
          $projectID = ($response.Content | ConvertFrom-Json).data.organization.projectsV2.nodes | Where-Object { $_.title -like "*${{ needs.get-team-name.outputs.team }}*" } | Select-Object -First 1 -ExpandProperty id
          
          if (-not $projectID) {
              Write-Host "No project found for team ${{ needs.get-team-name.outputs.team }}."
              exit 1
          }
          
          Write-Host "Found Project ID: $projectID"
          echo "::set-output name=project_id::$projectID"
  get-project-data:
    name: Output GraphQL Query Result
    runs-on: ubuntu-latest
    needs: get-project-id
    outputs:
      project_data: ${{ steps.output_query.outputs.project_data }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Output GraphQL Query Result
        id: output_query
        shell: pwsh
        env:
          project_id: ${{ needs.get-project-id.outputs.project_id }}
          PAT: ${{ secrets.PAT }}
        run: |
          $PROJECT_ID = $env:project_id; $TOKEN = $env:PAT; $query = "{ node(id: `"$PROJECT_ID`") { ... on ProjectV2 { items(first: 100) { nodes { id fieldValues(first: 100) { nodes { ... on ProjectV2ItemFieldSingleSelectValue { field { ... on ProjectV2Field { name } } name } ... on ProjectV2ItemFieldTextValue { field { ... on ProjectV2Field { name } } text } } } content { ... on Issue { title assignees(first: 10) { nodes { login } } } ... on PullRequest { title assignees(first: 10) { nodes { login } } } } } } } } } }"; $headers = @{ Authorization = "Bearer $TOKEN"; "Content-Type" = "application/json" }; $body = @{ query = $query } | ConvertTo-Json; $response = Invoke-WebRequest -Uri "https://api.github.com/graphql" -Method Post -Headers $headers -Body $body; Write-Host $response.Content; echo "::set-output name=project_data::$($response.Content)"
  count_issues:
    name: Count Issues by Column and Assignee
    runs-on: ubuntu-latest
    needs: get-project-data
    outputs:
      issue_counts: ${{ steps.count_issues.outputs.issue_counts }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Count Issues by Column and Assignee
        id: count_issues
        shell: pwsh
        env:
          project_data: ${{ needs.get-project-data.outputs.project_data }}
        run: |
          Write-Host "Starting issue count process"
          $data = $env:project_data | ConvertFrom-Json
          Write-Host "Project Data JSON: $($data | ConvertTo-Json -Depth 10)"
          $issueCounts = @{}
          foreach ($item in $data.data.node.items.nodes) {
            Write-Host "Processing item: $($item.id)"
            $columnField = $item.fieldValues.nodes | Where-Object { $_.name -eq "Status" -or $_.name -eq "testing" -or $_.name -eq "Done" -or $_.name -eq "In Progress" -or $_.name -eq "Todo" }
            if ($null -ne $columnField) {
              Write-Host "Found column field: $($columnField | ConvertTo-Json -Depth 10)"
              $column = $columnField.name
              Write-Host "Processing column: $column"
              if ($null -ne $column) {
                $assignees = $item.content.assignees.nodes | Select-Object -ExpandProperty login
                foreach ($assignee in $assignees) {
                  Write-Host "Processing assignee: $assignee"
                  if (-not $issueCounts.ContainsKey($column)) {
                    $issueCounts[$column] = @{}
                  }
                  if (-not $issueCounts[$column].ContainsKey($assignee)) {
                    $issueCounts[$column][$assignee] = 0
                  }
                  $issueCounts[$column][$assignee]++
                }
              }
            } else {
              Write-Host "No column field found for item: $($item.id)"
            }
          }
          foreach ($column in $issueCounts.Keys) {
            Write-Host "Column: $column"
            foreach ($assignee in $issueCounts[$column].Keys) {
              Write-Host "  Assignee: $assignee, Count: $($issueCounts[$column][$assignee])"
            }
          }
          $issueCountsJson = $issueCounts | ConvertTo-Json -Depth 10
          Write-Host "Issue Counts JSON: $issueCountsJson"  # Debugging: Output the issue counts JSON
          $issueCountsJson | Out-File issue_counts.json
          echo "::set-output name=issue_counts::$issueCountsJson"
          Write-Host "Issue count process completed"

      - name: Upload issue counts
        uses: actions/upload-artifact@v3
        with:
          name: issue_counts
          path: issue_counts.json

  generate-ascii-table:
    name: Generate ASCII Table
    runs-on: ubuntu-latest
    needs: count_issues
    outputs:
      ascii_table: ${{ steps.generate_table.outputs.ascii_table }}
    steps:
      - name: Download issue counts
        uses: actions/download-artifact@v3
        with:
          name: issue_counts

      - name: Generate ASCII Table
        id: generate_table
        shell: pwsh
        run: |
          $issueCounts = Get-Content issue_counts.json
          if (-not $issueCounts) {
            Write-Host "ISSUE_COUNTS is empty or not set"
            exit 1
          }
          $issueCounts = $issueCounts | ConvertFrom-Json
      
          # Collect all assignees
          $assignees = @{}
          foreach ($column in $issueCounts.PSObject.Properties.Name) {
            foreach ($assignee in $issueCounts.$column.PSObject.Properties.Name) {
              if (-not $assignees.ContainsKey($assignee)) {
                $assignees[$assignee] = @{}
              }
              $assignees[$assignee][$column] = $issueCounts.$column.$assignee
            }
          }
      
          # Define the column order and set a consistent width for each cell
          $columns = @("Todo", "In Progress", "testing", "Done")
          $cellWidth = 15  # Adjust this value as needed
      
          # Generate the table header
          $header = ($columns | ForEach-Object { $_.PadRight($cellWidth) }) -join " | "
          $separator = ($columns | ForEach-Object { "-" * $cellWidth }) -join "-|"
          $table = "| $header |`n| $separator |`n"
      
          # Generate the table rows
          foreach ($assignee in $assignees.Keys) {
            $row = "|"
            foreach ($column in $columns) {
              $count = if ($assignees[$assignee].ContainsKey($column)) { "${assignee}: $($assignees[$assignee][$column])" } else { "${assignee}: 0" }
              $row += " " + $count.PadRight($cellWidth) + " |"
            }
            $table += "$row`n"
          }
      
          Write-Host "ASCII Table:`n$table"
          $table | Out-File ascii_table.txt
          echo "::set-output name=ascii_table::$table"

      - name: Upload ASCII Table
        uses: actions/upload-artifact@v3
        with:
          name: ascii_table
          path: ascii_table.txt

  send-to-slack:
    name: Send Report to Slack
    runs-on: ubuntu-latest
    needs: [generate-ascii-table, get-team-name]
    steps:
      - name: Download ASCII Table
        uses: actions/download-artifact@v3
        with:
          name: ascii_table

      - name: Read ASCII Table
        id: read_ascii_table
        run: |
          table=$(cat ascii_table.txt)
          echo "ASCII Table Content:"
          printf "%s\n" "$table"  # Use printf for better handling of multiline text
          echo "$table" > ascii_table_content.txt
          echo "ascii_table_content<<EOF" >> $GITHUB_ENV
          cat ascii_table_content.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "TEAM_TO_CHANNEL: ${{ env.TEAM_TO_CHANNEL }}"
          echo "TEAM: ${{ env.TEAM }}"
          echo "ORG_NAME: ${{ env.ORG_NAME }}"
          echo "Slack Channel: ${{ fromJSON(env.TEAM_TO_CHANNEL)[needs.get-team-name.outputs.team] }}"
          echo "ASCII Table:"
          cat ascii_table_content.txt

      - name: Debug Slack Text
        run: |
          table=$(cat ascii_table.txt)
          echo "Slack Text:"
          printf "📊 *Kanban Board Status* 📊\n"
          printf '```\n%s\n```\n' "$table"

      - name: Send Report to Slack
        uses: archive/github-actions-slack@v2.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: ${{ fromJSON(env.TEAM_TO_CHANNEL)[needs.get-team-name.outputs.team] }}
          slack-text: |
            📊 *Kanban Board Status* 📊
            ```
            $(cat ascii_table.txt)
            ```